### ISSUE TITLE
Is stats available?

### ISSUE THREAD

**Issue by vasyl-shumskyi** [overlookmotel/require-folder-tree#4]
Does this awesome module check for [fs.stats](https://nodejs.org/api/fs.html#fs_class_fs_stats) info? 

Thanks!

**Comment by overlookmotel** [comment]
Thanks for the compliment!

Yes it does call `fs.statSync()` internally to check if each path is a folder or not - see here:

https://github.com/overlookmotel/require-folder-tree/blob/cdbb533149a45a283f8739672ec52e326eb75ba1/lib/index.js#L67

But question is: How to expose the stat objects to the user? The simplicity of the module is that you call the main method and get the `require()`-ed contents of the files. So how to return the stats too without complicating that API?

You got a suggestion for a nice API to do this?

**Comment by vasyl-shumskyi** [comment]
I see what you mean.. Will think this over.

**Comment by overlookmotel** [comment]
Closing this as no response from OP.
